id: ADDING_TREES

version: 0.4.0

author: PackFromScratch

addons:
  language-yaml: 0.1.+
  chunk-generator-noise-3d: 0.1.+
  config-noise-function: 0.1.+
  palette-block-shortcut: 0.1.+
  config-biome: 0.1.+
  biome-provider-single: 0.1.+
  biome-provider-pipeline-v2: "1.+"

  config-palette: 0.1.+

  config-feature: 0.1.+
  config-distributors: 0.1.+
  config-locators: 0.1.+
  structure-block-shortcut: "1.+"
  generation-stage-feature: "1.+"

  structure-sponge-loader: 0.1.+

generator: NOISE_3D

biomes:
  type: PIPELINE
  resolution: 4
  blend:
    amplitude: 2
    sampler:
      type: OPEN_SIMPLEX_2
      frequency: 0.1
  pipeline:
    source:
      type: SAMPLER
      sampler:
        dimensions: 2
        type: CONSTANT
      biomes:
        - land: 1
    stages:
      - type: REPLACE
        sampler:
          type: OPEN_SIMPLEX_2
          frequency: 0.04
        from: land
        to:
          - FIRST_BIOME: 1
          - SECOND_BIOME: 1

stages:
  # The trees generation stage will come before flora, making it generate first.
  - id: trees
    type: FEATURE

  - id: flora
    type: FEATURE
