id: ADDING_GRASS

version: 0.3.0

author: PackFromScratch

addons:
  language-yaml: 0.1.+
  chunk-generator-noise-3d: 0.1.+
  config-noise-function: 0.1.+
  palette-block-shortcut: 0.1.+
  config-biome: 0.1.+
  biome-provider-single: 0.1.+

  config-palette: 0.1.+

  config-feature: 0.1.+
  config-distributors: 0.1.+
  config-locators: 0.1.+
  structure-block-shortcut: "1.+"
  generation-stage-feature: "1.+"

generator: NOISE_3D

biomes:
  type: SINGLE
  biome: FIRST_BIOME

# Generation stages that come after the initial chunk generation
stages:
  - id: flora
    type: FEATURE
